export interface Surah {
  number: number;
  name_arabic: string;
  name_english: string;
  ayah_count: number;
}

export const SURAHS: Surah[] = [
  { number: 1, name_arabic: 'الفاتحة', name_english: 'Al-Fatihah', ayah_count: 7 },
  { number: 2, name_arabic: 'البقرة', name_english: 'Al-Baqarah', ayah_count: 286 },
  { number: 3, name_arabic: 'آل عمران', name_english: 'Ali Imran', ayah_count: 200 },
  { number: 4, name_arabic: 'النساء', name_english: 'An-Nisa', ayah_count: 176 },
  { number: 5, name_arabic: 'المائدة', name_english: 'Al-Maidah', ayah_count: 120 },
  { number: 6, name_arabic: 'الأنعام', name_english: 'Al-Anam', ayah_count: 165 },
  { number: 7, name_arabic: 'الأعراف', name_english: 'Al-Araf', ayah_count: 206 },
  { number: 8, name_arabic: 'الأنفال', name_english: 'Al-Anfal', ayah_count: 75 },
  { number: 9, name_arabic: 'التوبة', name_english: 'At-Tawbah', ayah_count: 129 },
  { number: 10, name_arabic: 'يونس', name_english: 'Yunus', ayah_count: 109 },
  { number: 11, name_arabic: 'هود', name_english: 'Hud', ayah_count: 123 },
  { number: 12, name_arabic: 'يوسف', name_english: 'Yusuf', ayah_count: 111 },
  { number: 13, name_arabic: 'الرعد', name_english: 'Ar-Rad', ayah_count: 43 },
  { number: 14, name_arabic: 'إبراهيم', name_english: 'Ibrahim', ayah_count: 52 },
  { number: 15, name_arabic: 'الحجر', name_english: 'Al-Hijr', ayah_count: 99 },
  { number: 16, name_arabic: 'النحل', name_english: 'An-Nahl', ayah_count: 128 },
  { number: 17, name_arabic: 'الإسراء', name_english: 'Al-Isra', ayah_count: 111 },
  { number: 18, name_arabic: 'الكهف', name_english: 'Al-Kahf', ayah_count: 110 },
  { number: 19, name_arabic: 'مريم', name_english: 'Maryam', ayah_count: 98 },
  { number: 20, name_arabic: 'طه', name_english: 'Taha', ayah_count: 135 },
  { number: 21, name_arabic: 'الأنبياء', name_english: 'Al-Anbiya', ayah_count: 112 },
  { number: 22, name_arabic: 'الحج', name_english: 'Al-Hajj', ayah_count: 78 },
  { number: 23, name_arabic: 'المؤمنون', name_english: 'Al-Muminun', ayah_count: 118 },
  { number: 24, name_arabic: 'النور', name_english: 'An-Nur', ayah_count: 64 },
  { number: 25, name_arabic: 'الفرقان', name_english: 'Al-Furqan', ayah_count: 77 },
  { number: 26, name_arabic: 'الشعراء', name_english: 'Ash-Shuara', ayah_count: 227 },
  { number: 27, name_arabic: 'النمل', name_english: 'An-Naml', ayah_count: 93 },
  { number: 28, name_arabic: 'القصص', name_english: 'Al-Qasas', ayah_count: 88 },
  { number: 29, name_arabic: 'العنكبوت', name_english: 'Al-Ankabut', ayah_count: 69 },
  { number: 30, name_arabic: 'الروم', name_english: 'Ar-Rum', ayah_count: 60 },
  { number: 31, name_arabic: 'لقمان', name_english: 'Luqman', ayah_count: 34 },
  { number: 32, name_arabic: 'السجدة', name_english: 'As-Sajdah', ayah_count: 30 },
  { number: 33, name_arabic: 'الأحزاب', name_english: 'Al-Ahzab', ayah_count: 73 },
  { number: 34, name_arabic: 'سبأ', name_english: 'Saba', ayah_count: 54 },
  { number: 35, name_arabic: 'فاطر', name_english: 'Fatir', ayah_count: 45 },
  { number: 36, name_arabic: 'يس', name_english: 'Ya-Sin', ayah_count: 83 },
  { number: 37, name_arabic: 'الصافات', name_english: 'As-Saffat', ayah_count: 182 },
  { number: 38, name_arabic: 'ص', name_english: 'Sad', ayah_count: 88 },
  { number: 39, name_arabic: 'الزمر', name_english: 'Az-Zumar', ayah_count: 75 },
  { number: 40, name_arabic: 'غافر', name_english: 'Ghafir', ayah_count: 85 },
  { number: 41, name_arabic: 'فصلت', name_english: 'Fussilat', ayah_count: 54 },
  { number: 42, name_arabic: 'الشورى', name_english: 'Ash-Shura', ayah_count: 53 },
  { number: 43, name_arabic: 'الزخرف', name_english: 'Az-Zukhruf', ayah_count: 89 },
  { number: 44, name_arabic: 'الدخان', name_english: 'Ad-Dukhan', ayah_count: 59 },
  { number: 45, name_arabic: 'الجاثية', name_english: 'Al-Jathiyah', ayah_count: 37 },
  { number: 46, name_arabic: 'الأحقاف', name_english: 'Al-Ahqaf', ayah_count: 35 },
  { number: 47, name_arabic: 'محمد', name_english: 'Muhammad', ayah_count: 38 },
  { number: 48, name_arabic: 'الفتح', name_english: 'Al-Fath', ayah_count: 29 },
  { number: 49, name_arabic: 'الحجرات', name_english: 'Al-Hujurat', ayah_count: 18 },
  { number: 50, name_arabic: 'ق', name_english: 'Qaf', ayah_count: 45 },
  { number: 51, name_arabic: 'الذاريات', name_english: 'Adh-Dhariyat', ayah_count: 60 },
  { number: 52, name_arabic: 'الطور', name_english: 'At-Tur', ayah_count: 49 },
  { number: 53, name_arabic: 'النجم', name_english: 'An-Najm', ayah_count: 62 },
  { number: 54, name_arabic: 'القمر', name_english: 'Al-Qamar', ayah_count: 55 },
  { number: 55, name_arabic: 'الرحمن', name_english: 'Ar-Rahman', ayah_count: 78 },
  { number: 56, name_arabic: 'الواقعة', name_english: 'Al-Waqiah', ayah_count: 96 },
  { number: 57, name_arabic: 'الحديد', name_english: 'Al-Hadid', ayah_count: 29 },
  { number: 58, name_arabic: 'المجادلة', name_english: 'Al-Mujadilah', ayah_count: 22 },
  { number: 59, name_arabic: 'الحشر', name_english: 'Al-Hashr', ayah_count: 24 },
  { number: 60, name_arabic: 'الممتحنة', name_english: 'Al-Mumtahanah', ayah_count: 13 },
  { number: 61, name_arabic: 'الصف', name_english: 'As-Saff', ayah_count: 14 },
  { number: 62, name_arabic: 'الجمعة', name_english: 'Al-Jumuah', ayah_count: 11 },
  { number: 63, name_arabic: 'المنافقون', name_english: 'Al-Munafiqun', ayah_count: 11 },
  { number: 64, name_arabic: 'التغابن', name_english: 'At-Taghabun', ayah_count: 18 },
  { number: 65, name_arabic: 'الطلاق', name_english: 'At-Talaq', ayah_count: 12 },
  { number: 66, name_arabic: 'التحريم', name_english: 'At-Tahrim', ayah_count: 12 },
  { number: 67, name_arabic: 'الملك', name_english: 'Al-Mulk', ayah_count: 30 },
  { number: 68, name_arabic: 'القلم', name_english: 'Al-Qalam', ayah_count: 52 },
  { number: 69, name_arabic: 'الحاقة', name_english: 'Al-Haqqah', ayah_count: 52 },
  { number: 70, name_arabic: 'المعارج', name_english: 'Al-Maarij', ayah_count: 44 },
  { number: 71, name_arabic: 'نوح', name_english: 'Nuh', ayah_count: 28 },
  { number: 72, name_arabic: 'الجن', name_english: 'Al-Jinn', ayah_count: 28 },
  { number: 73, name_arabic: 'المزمل', name_english: 'Al-Muzzammil', ayah_count: 20 },
  { number: 74, name_arabic: 'المدثر', name_english: 'Al-Muddaththir', ayah_count: 56 },
  { number: 75, name_arabic: 'القيامة', name_english: 'Al-Qiyamah', ayah_count: 40 },
  { number: 76, name_arabic: 'الإنسان', name_english: 'Al-Insan', ayah_count: 31 },
  { number: 77, name_arabic: 'المرسلات', name_english: 'Al-Mursalat', ayah_count: 50 },
  { number: 78, name_arabic: 'النبأ', name_english: 'An-Naba', ayah_count: 40 },
  { number: 79, name_arabic: 'النازعات', name_english: 'An-Naziat', ayah_count: 46 },
  { number: 80, name_arabic: 'عبس', name_english: 'Abasa', ayah_count: 42 },
  { number: 81, name_arabic: 'التكوير', name_english: 'At-Takwir', ayah_count: 29 },
  { number: 82, name_arabic: 'الإنفطار', name_english: 'Al-Infitar', ayah_count: 19 },
  { number: 83, name_arabic: 'المطففين', name_english: 'Al-Mutaffifin', ayah_count: 36 },
  { number: 84, name_arabic: 'الإنشقاق', name_english: 'Al-Inshiqaq', ayah_count: 25 },
  { number: 85, name_arabic: 'البروج', name_english: 'Al-Buruj', ayah_count: 22 },
  { number: 86, name_arabic: 'الطارق', name_english: 'At-Tariq', ayah_count: 17 },
  { number: 87, name_arabic: 'الأعلى', name_english: 'Al-Ala', ayah_count: 19 },
  { number: 88, name_arabic: 'الغاشية', name_english: 'Al-Ghashiyah', ayah_count: 26 },
  { number: 89, name_arabic: 'الفجر', name_english: 'Al-Fajr', ayah_count: 30 },
  { number: 90, name_arabic: 'البلد', name_english: 'Al-Balad', ayah_count: 20 },
  { number: 91, name_arabic: 'الشمس', name_english: 'Ash-Shams', ayah_count: 15 },
  { number: 92, name_arabic: 'الليل', name_english: 'Al-Layl', ayah_count: 21 },
  { number: 93, name_arabic: 'الضحى', name_english: 'Ad-Duha', ayah_count: 11 },
  { number: 94, name_arabic: 'الشرح', name_english: 'Ash-Sharh', ayah_count: 8 },
  { number: 95, name_arabic: 'التين', name_english: 'At-Tin', ayah_count: 8 },
  { number: 96, name_arabic: 'العلق', name_english: 'Al-Alaq', ayah_count: 19 },
  { number: 97, name_arabic: 'القدر', name_english: 'Al-Qadr', ayah_count: 5 },
  { number: 98, name_arabic: 'البينة', name_english: 'Al-Bayyinah', ayah_count: 8 },
  { number: 99, name_arabic: 'الزلزلة', name_english: 'Az-Zalzalah', ayah_count: 8 },
  { number: 100, name_arabic: 'العاديات', name_english: 'Al-Adiyat', ayah_count: 11 },
  { number: 101, name_arabic: 'القارعة', name_english: 'Al-Qariah', ayah_count: 11 },
  { number: 102, name_arabic: 'التكاثر', name_english: 'At-Takathur', ayah_count: 8 },
  { number: 103, name_arabic: 'العصر', name_english: 'Al-Asr', ayah_count: 3 },
  { number: 104, name_arabic: 'الهمزة', name_english: 'Al-Humazah', ayah_count: 9 },
  { number: 105, name_arabic: 'الفيل', name_english: 'Al-Fil', ayah_count: 5 },
  { number: 106, name_arabic: 'قريش', name_english: 'Quraysh', ayah_count: 4 },
  { number: 107, name_arabic: 'الماعون', name_english: 'Al-Maun', ayah_count: 7 },
  { number: 108, name_arabic: 'الكوثر', name_english: 'Al-Kawthar', ayah_count: 3 },
  { number: 109, name_arabic: 'الكافرون', name_english: 'Al-Kafirun', ayah_count: 6 },
  { number: 110, name_arabic: 'النصر', name_english: 'An-Nasr', ayah_count: 3 },
  { number: 111, name_arabic: 'المسد', name_english: 'Al-Masad', ayah_count: 5 },
  { number: 112, name_arabic: 'الإخلاص', name_english: 'Al-Ikhlas', ayah_count: 4 },
  { number: 113, name_arabic: 'الفلق', name_english: 'Al-Falaq', ayah_count: 5 },
  { number: 114, name_arabic: 'الناس', name_english: 'An-Nas', ayah_count: 6 },
];

export interface QuranEdition {
  id: string;
  name: string;
}

export const QURAN_ARABIC_EDITION = 'quran-uthmani';

export const QURAN_TRANSLATIONS: { urdu: QuranEdition[]; english: QuranEdition[] } = {
  urdu: [
    { id: 'ur.jalandhry', name: 'Fateh Muhammad Jalandhry' },
    { id: 'ur.ahmedali', name: 'Ahmed Ali' },
    { id: 'ur.maududi', name: 'Abul Ala Maududi' },
  ],
  english: [
    { id: 'en.asad', name: 'Muhammad Asad' },
    { id: 'en.sahih', name: 'Saheeh International' },
    { id: 'en.pickthall', name: 'Pickthall' },
    { id: 'en.yusufali', name: 'Yusuf Ali' },
  ],
};
